[package]
name = "neat"
version = "0.1.0"
authors = ["trolleyman <cgtrolley@gmail.com>"]

[dependencies]
glium = "*"
cgmath = "*"
rusttype = "*"
unicode-normalization = "*"
log = "*"
simplelog = "*"
cfg-if = "*"

[target.'cfg(target_os = "windows")'.dependencies]
user32-sys = "*"

[target.'cfg(target_os = "macos")'.dependencies]


[target.'cfg(target_os = "linux")'.dependencies]
