[package]
name = "neat"
version = "0.1.0"
authors = ["Callum <cgtrolley@gmail.com>"]
build = "build/build.rs"

[lib]
name = "neat"

[dependencies]
glium = "0.13.5"
nalgebra = "0.6.0"
ncollide = "0.7.0"
nphysics3d = { git = "https://github.com/sebcrozet/nphysics.git" } # will be 0.2.3 (probably)
rusttype = "0.2.0"
unicode-normalization = "0.1.2"
log = "0.3.6"
simplelog = { git = "https://github.com/trolleyman/simplelog.rs" }
cfg-if = "0.1.0"
image = "0.8.0"

[target.'cfg(target_os = "windows")'.dependencies]
user32-sys = "*"

[target.'cfg(target_os = "macos")'.dependencies]


[target.'cfg(target_os = "linux")'.dependencies]

[[example]]
name = "solar"
path = "examples/solar.rs"
[[example]]
name = "balls"
path = "examples/balls.rs"
[[example]]
name = "rot_test"
path = "examples/rot_test.rs"
[[example]]
name = "spaceballs"
path = "examples/spaceballs.rs"

[[bin]]
name = "neat"
path = "src/main.rs"
doc = false
