[package]
name = "neat"
version = "0.1.0"
authors = ["trolleyman <cgtrolley@gmail.com>"]

[dependencies]
glium = "0.13.5"
nalgebra = "0.6.0"
ncollide = "0.7.0"
nphysics3d = { git = "https://github.com/sebcrozet/nphysics.git" } # 0.2.2
rusttype = "0.2.0"
unicode-normalization = "0.1.2"
log = "0.3.6"
simplelog = "0.1.0"
cfg-if = "0.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
user32-sys = "*"

[target.'cfg(target_os = "macos")'.dependencies]


[target.'cfg(target_os = "linux")'.dependencies]
